### ISSUE TITLE
No pubDate specified in RSS

### ISSUE THREAD

**Issue by AlexDaniel** [MarjanaVoronina/oppejoud.ee#3]
RSS was added in [this commit](https://github.com/MarjanaVoronina/oppejoud.ee/commit/80e7a434ac1a93d3443ad4eaa17a799503214de6) and is accessible at [this link](https://oppejoud.ee/?action=rss).

However, ``pubDate `` is not specified for any of the items.

I am not sure how RSS readers will understand this, but I assume most will use current date. This is very inconvenient if you are not fetching the data regularly.

**Comment by MarjanaVoronina** [comment]
Fixed in 6135c6b.
